language: java

env:
  GIT_SSH=$TRAVIS_BUILD_DIR/.travis/ssh.sh;

before_install:
  openssl aes-256-cbc -K $encrypted_f6092a3822f4_key -iv $encrypted_f6092a3822f4_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d

after_success: 
  #!/bin/bash

  if ([ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == false ]); then
    chmod 600 .travis/id_rsa;
    git push --force ssh://55f6e9550c1e668a840000cb@reportsqat-perfmon4j.rhcloud.com/~/git/reportsqat.git/ travispushing:master;
  fi; 

