language: java

after_success: 
  #!/bin/bash
  if ["foo" == "foo"] then
    echo "yo"
  fi;
#  test ([ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) && echo "Yes, that's true." || echo "No, that's false."



#  ls
#  bash autodeploy.sh

